### PR TITLE
New CSS + HTML

### PR DESCRIPTION
**Pull request by SiddharthShyniben**
Hey Sreelak @Pupz124 this is a PR

### CODE REVIEW

**Comment by Pupz124** [comment]
OK BROTHER JUST DONT HACK ME OR ILL KILL YA
ARGH!!!!!

**Comment by SiddharthShyniben** [comment]
Hehe
go to commits tab

**Comment by SiddharthShyniben** [comment]
To see the changes

**Comment by Pupz124** [comment]
OK

**Comment by Pupz124** [comment]
OK

**Pull request merged**
